const db=require('../../database/db');
const C=require('../../config/constants');
function getUser(id){const u=db.prepare('SELECT * FROM users WHERE id=?').get(String(id));if(!u)throw Object.assign(new Error('User không tồn tại'),{status:404,code:'USER_NOT_FOUND'});return u}
function tx(fn){return db.transaction(fn)()}
function addBalance(id,amount,type='admin',note=''){amount=Number(amount);if(!Number.isSafeInteger(amount)||amount<0)throw new Error('Số tiền không hợp lệ');return tx(()=>{const u=getUser(id),next=u.balance+amount;db.prepare("UPDATE users SET balance=?,updated_at=strftime('%s','now') WHERE id=?").run(next,String(id));db.prepare('INSERT INTO transactions(user_id,type,amount,balance_before,balance_after,note) VALUES(?,?,?,?,?,?)').run(String(id),type,amount,u.balance,next,note);return next})}
function subtractBalance(id,amount,type='bet',note=''){amount=Number(amount);if(!Number.isSafeInteger(amount)||amount<0)throw new Error('Số tiền không hợp lệ');return tx(()=>{const u=getUser(id);if(u.balance<amount)throw Object.assign(new Error('Không đủ số dư'),{status:400,code:'INSUFFICIENT_BALANCE'});const next=u.balance-amount;db.prepare("UPDATE users SET balance=?,updated_at=strftime('%s','now') WHERE id=?").run(next,String(id));db.prepare('INSERT INTO transactions(user_id,type,amount,balance_before,balance_after,note) VALUES(?,?,?,?,?,?)').run(String(id),type,-amount,u.balance,next,note);return next})}
function canBet(id,amount){const u=getUser(id);return Number.isSafeInteger(amount)&&amount>=C.MIN_BET&&amount<=Math.floor(u.balance*C.MAX_BET_RATIO)}
function placeBet(id,amount,game){return tx(()=>{if(!canBet(id,amount))throw Object.assign(new Error('Cược phải từ 10.000 xu và không vượt 75% số dư'),{status:400,code:'INVALID_BET'});const before=subtractBalance(id,amount,'bet',game);const r=db.prepare('INSERT INTO bets(user_id,game,amount,result,payout,balance_after) VALUES(?,?,?,?,?,?)').run(String(id),game,amount,'pending',0,before);db.prepare("UPDATE users SET total_bets=total_bets+1,total_wagered=total_wagered+?,updated_at=strftime('%s','now') WHERE id=?").run(amount,String(id));return r.lastInsertRowid})}
function settleBet(betId,won,payout,multiplier,meta={}){return tx(()=>{const b=db.prepare('SELECT * FROM bets WHERE id=?').get(betId);if(!b||b.result!=='pending')throw new Error('Bet không hợp lệ');const u=getUser(b.user_id),newBal=u.balance+Number(payout);if(payout>0){db.prepare('UPDATE users SET balance=?,total_won=total_won+?,biggest_win=CASE WHEN ?>biggest_win THEN ? ELSE biggest_win END,total_wins=total_wins+1,win_streak=win_streak+1,max_win_streak=CASE WHEN win_streak+1>max_win_streak THEN win_streak+1 ELSE max_win_streak END WHERE id=?').run(newBal,payout,payout,payout,b.user_id)}else db.prepare('UPDATE users SET total_losses=total_losses+1,win_streak=0 WHERE id=?').run(b.user_id);db.prepare('UPDATE bets SET result=?,payout=?,multiplier=?,metadata=?,balance_after=? WHERE id=?').run(won?'win':'loss',payout,multiplier,JSON.stringify(meta),newBal,betId);if(payout>0)db.prepare('INSERT INTO transactions(user_id,type,amount,balance_before,balance_after,note) VALUES(?,?,?,?,?,?)').run(b.user_id,'payout',payout,u.balance,newBal,b.game);return{balance:newBal}})}
function getHistory(id,kind,limit=20,offset=0){const n=Math.min(Math.max(Number(limit)||20,1),100),o=Math.max(Number(offset)||0,0);return kind==='bets'?db.prepare('SELECT id,game,amount,result,payout,multiplier,created_at FROM bets WHERE user_id=? ORDER BY id DESC LIMIT ? OFFSET ?').all(String(id),n,o):db.prepare('SELECT id,type,amount,balance_before,balance_after,note,created_at FROM transactions WHERE user_id=? ORDER BY id DESC LIMIT ? OFFSET ?').all(String(id),n,o)}
module.exports={getUser,getBalance:id=>getUser(id).balance,addBalance,subtractBalance,canBet,placeBet,payoutBet:(id,p,m)=>settleBet(id,p>0,p,m),getTransactionHistory:(id,l,o)=>getHistory(id,'tx',l,o),getBetHistory:(id,l,o)=>getHistory(id,'bets',l,o),tx};
