const db=require('../../database/db'); const C=require('../../config/constants'); const {toBigInt}=require('../../utils/format'); const {nowSec}=require('../../utils/time');
function getUser(id){return db.prepare('SELECT * FROM users WHERE id=?').get(String(id));}
function getBalance(id){return toBigInt(getUser(id)?.balance||0)}
function logTx(userId,type,amount,before,after,note,meta){db.prepare('INSERT INTO transactions(user_id,type,amount,balance_before,balance_after,note,meta,created_at) VALUES(?,?,?,?,?,?,?,?)').run(String(userId),type,String(amount),String(before),String(after),note||null,meta?JSON.stringify(meta):null,nowSec())}
function addBalance(id,amount,type='credit',note=''){const a=toBigInt(amount);if(a<0n)throw new Error('Negative amount');const row=getUser(id);if(!row)throw new Error('User not found');const before=toBigInt(row.balance),after=before+a;db.prepare('UPDATE users SET balance=?,updated_at=? WHERE id=?').run(after.toString(),nowSec(),String(id));logTx(id,type,a,before,after,note);return after}
function subtractBalance(id,amount,type='debit',note=''){const a=toBigInt(amount);if(a<=0n)throw new Error('Invalid amount');const row=getUser(id);if(!row)throw new Error('User not found');const before=toBigInt(row.balance);if(before<a)throw new Error('Insufficient balance');const after=before-a;db.prepare('UPDATE users SET balance=?,updated_at=? WHERE id=?').run(after.toString(),nowSec(),String(id));logTx(id,type,(-a).toString(),before,after,note);return after}
function canBet(id,amount){const a=toBigInt(amount);const b=getBalance(id);return a>=C.MIN_BET && a*100n<=b*C.MAX_BET_RATIO;}
function placeBet(id,amount,game){const a=toBigInt(amount);if(!canBet(id,a))throw new Error('Invalid bet');return db.transaction(()=>{const before=getBalance(id);const after=before-a;db.prepare('UPDATE users SET balance=?,total_bets=total_bets+1,total_wagered=?,updated_at=? WHERE id=?').run(after.toString(),(toBigInt(getUser(id).total_wagered||0)+a).toString(),nowSec(),String(id));logTx(id,'bet',(-a).toString(),before,after,game);const r=db.prepare('INSERT INTO bets(user_id,game,amount,result,payout,multiplier,created_at) VALUES(?,?,?,?,?,?,?)').run(String(id),game,a.toString(),'pending','0',0,nowSec());return r.lastInsertRowid;})();}
function payoutBet(betId,payout,multiplier,result='win'){db.transaction(()=>{const bet=db.prepare('SELECT * FROM bets WHERE id=?').get(betId);if(!bet||bet.result!=='pending')throw new Error('Bet closed');const p=toBigInt(payout);const user=getUser(bet.user_id);const before=toBigInt(user.balance);const after=before+p;db.prepare('UPDATE users SET balance=?,total_won=?,biggest_win=?,updated_at=? WHERE id=?').run(after.toString(),(toBigInt(user.total_won||0)+p).toString(),(p>toBigInt(user.biggest_win||0)?p:toBigInt(user.biggest_win||0)).toString(),nowSec(),bet.user_id);db.prepare('UPDATE bets SET result=?,payout=?,multiplier=?,balance_after=? WHERE id=?').run(result,p.toString(),Number(multiplier||0),after.toString(),betId);if(result==='win')db.prepare('UPDATE users SET total_wins=total_wins+1,win_streak=win_streak+1,max_win_streak=MAX(max_win_streak,win_streak+1) WHERE id=?').run(bet.user_id);else db.prepare('UPDATE users SET total_losses=total_losses+1,win_streak=0 WHERE id=?').run(bet.user_id);logTx(bet.user_id,'payout',p.toString(),before,after,bet.game);})();}
function transfer(from,to,amount){const a=toBigInt(amount);if(a<=0n||String(from)===String(to))throw new Error('Invalid transfer');return db.transaction(()=>{subtractBalance(from,a,'transfer_out',`to:${to}`);addBalance(to,a,'transfer_in',`from:${from}`);return true;})();}
function addBank(id,amount){const a=toBigInt(amount);subtractBalance(id,a,'bank_deposit');db.prepare('UPDATE users SET bank=? WHERE id=?').run((toBigInt(getUser(id).bank)+a).toString(),String(id));return toBigInt(getUser(id).bank)}
function subtractBank(id,amount){const a=toBigInt(amount);const u=getUser(id),b=toBigInt(u.bank);if(b<a)throw new Error('Insufficient bank');db.prepare('UPDATE users SET bank=? WHERE id=?').run((b-a).toString(),String(id));addBalance(id,a,'bank_withdraw');return b-a}
function getTransactionHistory(id,limit=50,offset=0){return db.prepare('SELECT * FROM transactions WHERE user_id=? ORDER BY id DESC LIMIT ? OFFSET ?').all(String(id),limit,offset)}
function getBetHistory(id,limit=50,offset=0){return db.prepare('SELECT * FROM bets WHERE user_id=? ORDER BY id DESC LIMIT ? OFFSET ?').all(String(id),limit,offset)}
module.exports={getBalance,addBalance,subtractBalance,transfer,addBank,subtractBank,canBet,placeBet,payoutBet,getTransactionHistory,getBetHistory,getUser};
