const db=require('../../database/db'); const C=require('../../config/constants');
function getAllPets(includeHidden=false){return includeHidden?db.prepare('SELECT * FROM pets ORDER BY order_index').all():db.prepare('SELECT * FROM pets WHERE hidden=0 ORDER BY order_index').all()}
function getPetById(id){return db.prepare('SELECT * FROM pets WHERE id=?').get(String(id))}
function getUserPets(id){return db.prepare('SELECT p.*,up.level,up.equipped,up.acquired_at FROM user_pets up JOIN pets p ON p.id=up.pet_id WHERE up.user_id=? ORDER BY p.order_index').all(String(id))}
function buyPet(uid,pid){return db.transaction(()=>{const p=getPetById(pid); if(!p||p.hidden) throw Object.assign(new Error('Pet không tồn tại'),{status:404}); if(db.prepare('SELECT 1 FROM user_pets WHERE user_id=? AND pet_id=?').get(uid,pid)) throw Object.assign(new Error('Bạn đã sở hữu pet'),{status:400}); const u=db.prepare('SELECT balance FROM users WHERE id=?').get(uid); if(u.balance<p.price) throw Object.assign(new Error('Không đủ xu'),{status:400}); db.prepare('UPDATE users SET balance=balance-? WHERE id=?').run(p.price,uid); db.prepare('INSERT INTO user_pets(user_id,pet_id) VALUES(?,?)').run(uid,pid); db.prepare('INSERT INTO transactions(user_id,type,amount,balance_before,balance_after,note) VALUES(?,?,?,?,?,?)').run(uid,'pet_buy',-p.price,u.balance,u.balance-p.price,pid); return true;})()}
function sellPet(uid,pid){return db.transaction(()=>{const p=getPetById(pid); const own=db.prepare('SELECT equipped FROM user_pets WHERE user_id=? AND pet_id=?').get(uid,pid); if(!p||!own) throw Object.assign(new Error('Không sở hữu pet'),{status:400}); if(own.equipped) throw Object.assign(new Error('Hãy tháo trang bị trước khi bán'),{status:400}); const refund=Math.floor(p.price*C.PET_SELL_RATIO); const u=db.prepare('SELECT balance FROM users WHERE id=?').get(uid); db.prepare('DELETE FROM user_pets WHERE user_id=? AND pet_id=?').run(uid,pid); db.prepare('UPDATE users SET balance=balance+? WHERE id=?').run(refund,uid); db.prepare('INSERT INTO transactions(user_id,type,amount,balance_before,balance_after,note) VALUES(?,?,?,?,?,?)').run(uid,'pet_sell',refund,u.balance,u.balance+refund,pid); return refund;})()}
function equipPet(uid,pid){return db.transaction(()=>{if(!db.prepare('SELECT 1 FROM user_pets WHERE user_id=? AND pet_id=?').get(uid,pid)) throw new Error('Chưa sở hữu pet'); db.prepare('UPDATE user_pets SET equipped=0 WHERE user_id=?').run(uid); db.prepare('UPDATE user_pets SET equipped=1 WHERE user_id=? AND pet_id=?').run(uid,pid); db.prepare('UPDATE users SET pet_equipped=? WHERE id=?').run(pid,uid); return true;})()}
function unequipPet(uid){db.prepare('UPDATE user_pets SET equipped=0 WHERE user_id=?').run(uid); db.prepare('UPDATE users SET pet_equipped=NULL WHERE id=?').run(uid); return true}
function getEquippedPet(uid){return db.prepare('SELECT p.*,up.level FROM user_pets up JOIN pets p ON p.id=up.pet_id WHERE up.user_id=? AND up.equipped=1').get(uid)||null}
function applyPetBonus(uid,amount,type){const p=getEquippedPet(uid); if(!p) return Math.floor(amount); const bonus=(type==='money'?p.money_bonus:p.xp_bonus)*(1+(p.level-1)*0.1); return Math.floor(amount*(1+bonus));}
function upgradePet(uid,pid){return db.transaction(()=>{const row=db.prepare('SELECT up.level,p.price,p.max_level FROM user_pets up JOIN pets p ON p.id=up.pet_id WHERE up.user_id=? AND up.pet_id=?').get(uid,pid); if(!row) throw new Error('Chưa sở hữu pet'); if(row.level>=row.max_level) throw new Error('Pet đã đạt cấp tối đa'); const cost=Math.floor(row.price*0.2*row.level); const u=db.prepare('SELECT balance FROM users WHERE id=?').get(uid); if(u.balance<cost) throw new Error('Không đủ xu'); db.prepare('UPDATE users SET balance=balance-? WHERE id=?').run(cost,uid); db.prepare('UPDATE user_pets SET level=level+1 WHERE user_id=? AND pet_id=?').run(uid,pid); return {level:row.level+1,cost};})()}
function createPet(d){db.prepare('INSERT INTO pets(id,name,icon,money_bonus,xp_bonus,price,hidden,rarity,description,order_index) VALUES(?,?,?,?,?,?,?,?,?,?)').run(d.id,d.name,d.icon,d.money_bonus,d.xp_bonus,d.price,d.hidden?1:0,d.rarity||'custom',d.description||'',Date.now()); return getPetById(d.id)}
function updatePet(id,field,value){const allowed=new Set(['name','icon','money_bonus','xp_bonus','price','hidden','rarity','description']); if(!allowed.has(field)) throw new Error('Field không hợp lệ'); db.prepare(`UPDATE pets SET ${field}=? WHERE id=?`).run(value,id); return !!getPetById(id)}
function deletePet(id){return db.transaction(()=>{db.prepare('UPDATE users SET pet_equipped=NULL WHERE pet_equipped=?').run(id); db.prepare('DELETE FROM user_pets WHERE pet_id=?').run(id); return db.prepare('DELETE FROM pets WHERE id=?').run(id).changes>0})()}
module.exports={getAllPets,getPetById,getUserPets,buyPet,sellPet,equipPet,unequipPet,getEquippedPet,upgradePet,applyPetBonus,createPet,updatePet,deletePet};
