const db=require('../../database/db'); const {auth}=require('../middleware/auth'); const pets=require('../services/pet'); const eco=require('../services/economy'); const level=require('../services/level'); const energy=require('../services/energy'); const board=require('../services/leaderboard'); const bank=require('../services/bank'); const quest=require('../services/quest'); const ach=require('../services/achievement'); const coupon=require('../services/coupon'); const item=require('../services/item'); const clan=require('../services/clan'); const notification=require('../services/notification'); const chat=require('../services/chat'); const event=require('../services/event'); const season=require('../services/season'); const referral=require('../services/referral'); const trade=require('../services/trade'); const jackpot=require('../services/jackpot'); const C=require('../../config/constants');
const safe=x=>JSON.parse(JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString():v));
module.exports=(app)=>{
app.get('/api/me',auth,(req,res)=>res.json({user:safe(req.user),energy:energy.getEnergy(req.user.id),level:level.getLevel(req.user.id),pet:pets.getEquippedPet(req.user.id)}));
app.get('/api/profile',auth,(req,res)=>res.json({user:safe(eco.getUser(req.user.id)),pet:pets.getEquippedPet(req.user.id)}));
app.patch('/api/profile/name',auth,(req,res)=>{const name=String(req.body?.name||'').trim();if(!/^[\p{L}\p{N} _-]{1,32}$/u.test(name))return res.status(400).json({error:'Tên không hợp lệ'});const taken=db.prepare('SELECT id FROM users WHERE display_name=? AND id<>?').get(name,String(req.user.id));if(taken)return res.status(400).json({error:'Tên đã tồn tại'});const firstName=!req.user.display_name;if(!firstName&&name!==req.user.display_name){if(eco.getBalance(req.user.id)<C.RENAME_COST)return res.status(400).json({error:'Không đủ 5,000,000 xu'});eco.subtractBalance(req.user.id,C.RENAME_COST,'rename','profile name change')}const current=JSON.parse(req.user.settings||'{}');current.onboarded=true;db.prepare('UPDATE users SET display_name=?,settings=?,updated_at=? WHERE id=?').run(name,JSON.stringify(current),Math.floor(Date.now()/1000),String(req.user.id));res.json({ok:true,user:safe(eco.getUser(req.user.id))})});
app.patch('/api/profile/bio',auth,(req,res)=>{const bio=String(req.body?.bio||'').slice(0,160);db.prepare('UPDATE users SET bio=?,updated_at=? WHERE id=?').run(bio,Math.floor(Date.now()/1000),String(req.user.id));res.json({ok:true})});
app.patch('/api/settings',auth,(req,res)=>{const settings={...JSON.parse(req.user.settings||'{}'),...(req.body||{})};db.prepare('UPDATE users SET settings=? WHERE id=?').run(JSON.stringify(settings),String(req.user.id));res.json(settings)});
app.get('/api/games',auth,(_,res)=>res.json(require('../../data/games')));
app.get('/api/games/:code',auth,(req,res)=>{const g=require('../../data/games').find(x=>x.code===req.params.code);if(!g)return res.status(404).json({error:'Game not found'});res.json(g)});
app.get('/api/pets',auth,(req,res)=>res.json(pets.getAllPets(false)));
app.get('/api/pets/:id',auth,(req,res)=>{const p=pets.getPetById(req.params.id);if(!p)return res.status(404).json({error:'Pet not found'});res.json(p)});
app.get('/api/my-pets',auth,(req,res)=>res.json(pets.getUserPets(req.user.id)));
app.post('/api/pets/buy',auth,(req,res)=>res.json({ok:pets.buyPet(req.user.id,req.body.petId)}));
app.post('/api/pets/sell',auth,(req,res)=>res.json({refund:pets.sellPet(req.user.id,req.body.petId).toString()}));
app.post('/api/pets/equip',auth,(req,res)=>res.json({ok:pets.equipPet(req.user.id,req.body.petId)}));
app.post('/api/pets/unequip',auth,(req,res)=>res.json({ok:pets.unequipPet(req.user.id)}));
app.post('/api/pets/upgrade',auth,(req,res)=>res.json({ok:pets.upgradePet(req.user.id,req.body.petId)}));
app.get('/api/leaderboards',auth,(req,res)=>res.json(Object.fromEntries(['money','level','bank','login_streak','win_streak','wins'].map(t=>[t,board.get(t,20)]))));
app.get('/api/leaderboard/:type',auth,(req,res)=>res.json(board.get(req.params.type,100).map(safe)));
app.get('/api/bets',auth,(req,res)=>res.json(eco.getBetHistory(req.user.id,50,Number(req.query.offset||0)).map(safe)));
app.get('/api/transactions',auth,(req,res)=>res.json(eco.getTransactionHistory(req.user.id,50,Number(req.query.offset||0)).map(safe)));
app.get('/api/quests',auth,(req,res)=>res.json(quest.getUserQuests(req.user.id)));
app.post('/api/quests/:id/claim',auth,(req,res)=>res.json(quest.claimQuest(req.user.id,req.params.id)));
app.get('/api/achievements',auth,(req,res)=>res.json(ach.getUserAchievements(req.user.id)));
app.get('/api/achievement-catalog',auth,(req,res)=>res.json(ach.getAllAchievements()));
app.get('/api/inventory',auth,(req,res)=>res.json(item.getInventory(req.user.id)));
app.get('/api/shop/items',auth,(req,res)=>res.json(item.list()));
app.get('/api/notifications',auth,(req,res)=>res.json(notification.getUnread(req.user.id)));
app.post('/api/notifications/:id/read',auth,(req,res)=>res.json({ok:notification.markRead(req.user.id,req.params.id)}));
app.post('/api/notifications/read-all',auth,(req,res)=>res.json({ok:notification.markAllRead(req.user.id)}));
app.get('/api/clan',auth,(req,res)=>res.json(clan.getUserClan(req.user.id)));
app.get('/api/clans',auth,(req,res)=>res.json(clan.listClans(50,Number(req.query.offset||0))));
app.get('/api/chat/channels',auth,(req,res)=>res.json(chat.getChannels()));
app.get('/api/chat/messages/:channelId',auth,(req,res)=>res.json(chat.getMessages(Number(req.params.channelId),50,req.query.beforeId?Number(req.query.beforeId):undefined)));
app.post('/api/chat/messages',auth,(req,res)=>res.json(chat.sendMessage(req.user.id,Number(req.body.channelId),String(req.body.content||''))));
app.delete('/api/chat/messages/:id',auth,(req,res)=>res.json({ok:chat.deleteMessage(req.user.id,req.params.id)}));
app.patch('/api/chat/messages/:id',auth,(req,res)=>res.json({ok:chat.editMessage(req.user.id,req.params.id,String(req.body.content||''))}));
app.get('/api/events',auth,(req,res)=>res.json(event.getActiveEvents()));
app.get('/api/jackpot',auth,(req,res)=>res.json({amount:jackpot.getJackpot().toString()}));
app.get('/api/season',auth,(req,res)=>res.json(season.get(req.user.id,Number(req.query.season||1))||{user_id:req.user.id,season:Number(req.query.season||1),tier:0,xp:0,premium:0}));
app.get('/api/referrals',auth,(req,res)=>res.json(referral.getByUser(req.user.id)));
app.get('/api/trades',auth,(req,res)=>res.json(trade.listForUser(req.user.id)));
app.post('/api/trades',auth,(req,res)=>res.json(trade.createOffer(req.user.id,req.body.toUser,req.body.offerMoney||0,req.body.offerItems||[],req.body.offerPets||[],req.body.requestMoney||0,req.body.requestItems||[],req.body.requestPets||[],String(req.body.message||'').slice(0,200))));
app.post('/api/trades/:id/accept',auth,(req,res)=>res.json({ok:trade.acceptOffer(req.params.id,req.user.id)}));
app.post('/api/trades/:id/cancel',auth,(req,res)=>res.json({ok:trade.cancelOffer(req.params.id,req.user.id)}));
app.get('/api/bank',auth,(req,res)=>res.json({bank:bank.getBank(req.user.id).toString(),interestRate:C.BANK_INTEREST_DAILY,withdrawFee:C.BANK_WITHDRAW_FEE}));
app.post('/api/bank/deposit',auth,(req,res)=>res.json({bank:bank.deposit(req.user.id,req.body.amount).toString()}));
app.post('/api/bank/withdraw',auth,(req,res)=>res.json({bank:bank.withdraw(req.user.id,req.body.amount).toString()}));
app.post('/api/coupon/redeem',auth,(req,res)=>res.json(coupon.redeemCoupon(req.user.id,req.body.code)));
app.get('/api/coupons/:code',auth,(req,res)=>res.json(coupon.getCoupon(req.params.code)));
};
